config/routes.rb
Rails.application.routes.draw do
  get 'top' => 'homes#top'
  root "homes#top"
  get 'about' => 'homes#about'
  get 'admins/index'
  get 'admins/show'
  get 'admins/edit'
  get 'photos/index'
  get 'photos/show'
  get 'photos/edit'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # devise_for :customers
  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }

  # devise_for :admins
  devise_for :admins, controllers: {
   sessions: 'admins/sessions'
  }

  resources :photos do
  	resource :favorites, only: [:create, :destroy]
  	resource :comments, only: [:create]
  end
  resources :customers do
  	member do
  		get :favolist
  		get :destroy_cus
  		get :follower, :followed
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  resources :customers, only: [:show, :edit, :update]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :customer
	belongs_to :photo
	validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :favorites
  has_many :comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー
  has_many :following_customer, through: :follower, source: :followed # フォローしている人
  has_many :follower_customer, through: :followed, source: :follower # フォローしている人

  # フォローする
  def follow(customer_id)
    follower.create(followed_id: customer_id)
  end

  # フォローを外す
  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(customer)
    following_customer.include?(customer)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :customer
	belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :customer
	attachment :image
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	validates :place, presence: true
	validates :tag, presence: true
	default_scope -> { order(created_at: :desc) }
	def favorited_by?(customer)
		favorites.where(customer_id: customer.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :follower, class_name: "Customer"
belongs_to :followed, class_name: "Customer"
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
  def index
  	@customers = Customer.all
  end

  def show
  	@photos = Photo.all
  end

  def edit
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_customer!
	def create
		photo = Photo.find(params[:photo_id])
		comment = current_customer.comments.new(comment_params)
		comment.photo_id = photo.id
		comment.save
		redirect_to request.referer
	end

	private
	def comment_params
		params.require(:comment).permit(:comment)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_customer!

  def index
    @photos = Photo.page(params[:page]).reverse_order
  end

  def show
  	@photo = Photo.find(params[:id])
    geo_data = Geocoder.search(@photo.place)
    @lat = geo_data[0].data["lat"].to_f
    @lon = geo_data[0].data["lon"].to_f
    @comment = Comment.new
  end

  def new
  	@photo = Photo.new
  end

  def create
  	@photo = Photo.new(photo_params)
    @photo.customer = current_customer
  	if @photo.save
      flash[:notice] = "投稿できました！！"
  		redirect_to photos_path
  	else
  		render "new"
  	end
  end

  def edit
  	@photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)
    redirect_to photo_path(@photo.id)
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def photo_params
  	params.require(:photo).permit(:name, :title, :explain, :place, :tag, :image)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favolists_helper.rb
module FavolistsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admins/index.html.erb
<%= link_to "管理人専用：投稿一覧ページへ", admins_show_path, class: "btn btn-default" %>
<h2>管理人専用：会員一覧ページ</h2>
<table class="table table-striped">
<% @customers.each do |customer| %>
	<tr>
		<td>
			<%= attachment_image_tag(customer, :profile_image, :fill, 100,100, fallback: "no_image.jpg", size: "100x100", class: "img-circle") %>
		</td>
		<td>
			<h2><%= customer.name %></h2>
		</td>
		<td>
			<%= link_to "削除する", destroy_cus_customer_path(customer.id), class: "btn btn-danger", style: "margin-top: 30px;" %>
		</td>
	</tr>
<% end %>
</table>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/show.html.erb
<%= link_to "管理人専用会員一覧へ", admins_index_path, class: "btn btn-default" %>
<% @photos.each do |photo| %>
<table class="table table-striped">
	<tr>
		<td>
			<%= attachment_image_tag photo, :image, size: "300x200" %>
		</td>
		<td>
			<%= attachment_image_tag(photo.customer, :profile_image, :fill, 200,200, fallback: "no_image.jpg", class: "img-circle") %>
		</td>
		<td>
			<h2 style="margin-top: 80px;"><%= photo.customer.name %></h2>
		</td>
		<td>
			<%= link_to "削除する", photo_path(photo), method: :delete, class: "btn btn-danger", style: "margin-top: 80px;" %>
		</td>
	</tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoshopUT</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
      <div class="row">
        <div class="col-lg-12" style="background-color: green; width:100%; margin-top:50px;">
          <div class="nav navbar-nav navbar-left">
            <li style="margin: 10px; font-size: 30px;">
              <%= link_to "PhotoShopUT", root_path %>
            </li>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li style="margin: 10px;">
                <%= link_to destroy_admin_session_path, method: :delete do%><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>管理者ログアウト
                <% end %>
              </li>
            <% elsif customer_signed_in? %>
              <li style="margin: 10px;">
                <%= link_to customer_path(current_customer.id) do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>マイページ
                <% end %>
              </li>
              <li style="margin: 10px;">
                <%= link_to about_path do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>About
                <% end %>
              </li>
              <li style="margin: 10px;">
                <%= link_to destroy_customer_session_path, method: :delete do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>ログアウト
                <% end %>
              </li>
              <li> style="margin-top: 10px;">
              <%= link_to customers_path do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>投稿一覧
              </li>
            <% else %>
              <li style="margin: 10px;">
                <%= link_to new_customer_registration_path  do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>会員登録
                <% end %>
              </li>
              <li style="margin: 10px;">
                <%= link_to new_customer_session_path do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>ログイン
                <% end %>
              </li>
              <li style="margin: 10px;">
                <%= link_to about_path do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>About
                <% end %>
              </li>
              <li style="margin: 10px;">
                <%= link_to new_admin_session_path do %><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>管理人専用
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
  </header>
</body>
<%= yield %>
<div class="row">
  <div class="col-lg-12" style="background-color: green; width:100%; margin-top:50px; height: 50px;">

  </div>
</div>