config/routes.rb
Rails.application.routes.draw do
  get 'top' => 'homes#top'
  root "homes#top"
  get 'about' => 'homes#about'
  get 'admins/index'
  get 'admins/show'
  get 'admins/edit'
  get 'photos/index'
  get 'photos/show'
  get 'photos/edit'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # devise_for :customers
  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }

  # devise_for :admins
  devise_for :admins, controllers: {
   sessions: 'admins/sessions'
  }

  resources :photos do
  	resource :favorites, only: [:create, :destroy]
  	resource :comments, only: [:create]
  end
  resources :customers do
  	member do
  		get :favolist
  		get :destroy_cus
  		get :follower, :followed
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  resources :customers, only: [:show, :edit, :update]
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :favorites
  has_many :comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー
  has_many :following_customer, through: :follower, source: :followed # フォローしている人
  has_many :follower_customer, through: :followed, source: :follower # フォローしている人

  # フォローする
  def follow(customer_id)
    follower.create(followed_id: customer_id)
  end

  # フォローを外す
  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(customer)
    following_customer.include?(customer)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  def index
  	@photos = Photo.page(params[:page]).reverse_order
  end

  def show
  	@customer = Customer.find(params[:id])
  end

  def favolist
    @customer = Customer.find(params[:id])
      # ここからサンプルとして記述しますね @sakuma
    @favoList = Favorite.select(:photo_id).where(customer_id: @customer.id)
    @favophotolist = Photo.where(id: @favoList)
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def destroy_cus
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to request.referer
  end

  def update
  	@customer = Customer.find(params[:id])
  	@customer.update(customer_params)
  	redirect_to customer_path(@customer.id)
  end

  def follower
    @customer = Customer.find(params[:id])
  end

  def followed
    @customer =Customer.find(params[:id])
  end

  private
  def customer_params
  	params.require(:customer).permit(:name, :profile_image)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h1>ユーザー編集</h1>
<%= form_for(@customer, url: customer_path) do |f| %>
<% if @customer.errors.any? %>
<div id="error">
  <h2><%= @customer.errors.count %>件のエラーがあります。</h2>
  <% @customer.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
</div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <label>プロフィール画</label>
      <%= f.attachment_field :profile_image %>
    </div>
  </div>
  <br>
  <div class="col-sm-6">
    <label>アカウント名</label>
    <%= f.text_field :name, class:"form-control", placeholder:"アカウント名はこちら" %>
  </div>

  <div class="col-sm-6">
    <label>メールアドレス</label>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder:"メールアドレスはこちら" %>
  </div>

  <div class="col-sm-6">
    <%= f.submit "変更する", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
    <% end %>
  </div>
</div>

app/views/customers/favolist.html.erb
<h2>お気に入り投稿した一覧</h2>
<div class="container">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2">
			<% @favophotolist.each do |photo| %>
			<table class="table table-hover">
				<tr>
					<%= link_to photo_path(photo.id) do %>
					<%= attachment_image_tag photo, :image, size: "300x200" %>
					<% end %>
				</tr>
				<tr>
					<%= link_to customer_path(photo.customer.id) do %>
					<%= attachment_image_tag(photo.customer, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: "100x100", class: "img-circle") %>
					<%= photo.customer.name %>
					<% end %>
				</tr>
				<tr>
					@<%= photo.place %>
					#<%= photo.tag %>
				</tr>
				<tr>
					<% if photo.favorited_by?(current_customer) %>
					<%= link_to photo_favorites_path(photo), method: :delete do %>
					<span class="glyphicon glyphicon-heart-empty" aria-hidden="true" style="color: red;"></span>
					<%= photo.favorites.count %> いいね
					<% end %>
					<% else %>
					<%= link_to photo_favorites_path(photo), method: :post do %>
					<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
					<%= photo.favorites.count %> いいね
					<% end %>
					<% end %>
				</tr>
			</table>
			<% end %>
		</div>
	</div>
</div>

app/views/customers/followed.html.erb
<h2>フォロワー一覧</h2>
  <div class="container">
    <div class="row">
    	<div class="col-lg-8 col-lg-offset-2">
    		<% @customer.follower_customer.each do |customer| %>
    		<table class="table table-striped">
    			<tr>
    				<td>
    				<%= attachment_image_tag(customer, :profile_image, size: '100x100', fallback: "no_image.jpg", size: '100x100', style: "border-radius: 70%;") %>
    				</td>
    				<td>
    					<div style="margin-top: 50px;">
    					<%= link_to customer_path(customer.id) do %>
    					<%= customer.name %>
    					<% end %>
    					</div>
    				</td>
    				<td>
    					<div style="margin-top: 50px;">
    					<%= "投稿数：#{customer.photos.count}" %>
    					</div>
    				</td>
    			</tr>
    			<% end %>
    		</table>
    	</div>
    </div>
</div>

app/views/customers/follower.html.erb
<h2>フォロー一覧</h2>
  <div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <% @customer.following_customer.where.not(id: current_customer.id).each do |customer| %>
            <table class="table table-striped">
                <tr>
                    <td>
                    <%= attachment_image_tag(customer, :profile_image, size: '100x100', fallback: "no_image.jpg", size: '100x100', style: "border-radius: 70%;") %>
                    </td>
                    <td>
                        <div style="margin-top: 50px;">
                        <%= link_to customer_path(customer.id) do %>
                        <%= customer.name %>
                        <% end %>
                        </div>
                    </td>
                    <td>
                        <div style="margin-top: 50px;">
                        <%= "投稿数：#{customer.photos.count}" %>
                        </div>
                    </td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/customers/index.html.erb
<h1>投稿一覧</h1>
<div class ="container">
	<div class="row">
		<div class="col-lg-3">
			<div class="center_text">
				<%= attachment_image_tag(current_customer, :profile_image, :fill, 200,200, fallback: "no_image.jpg", size: '200x200', style: "border-radius: 70%;") %>
				<h3><%= current_customer.name %></h3>
				<div style="margin-top: 10px;">
					<%= link_to "フォロー数： #{current_customer.follower.count}", follower_customer_path(current_customer), class: "btn btn-default" %>
				</div>
				<div style="margin-top: 10px;">
					<%=link_to "フォロワー数： #{current_customer.followed.count}", followed_customer_path(current_customer), class: "btn btn-success" %>
				</div>
				<div style="margin-top: 10px;">
					<%= link_to "プロフィール編集", edit_customer_path(current_customer), class: "btn btn-default", style: "width: 150px;" %><br>
				</div>
				<div style="margin-top: 10px;">
					<%= link_to "投稿する", new_photo_path, class: "btn btn-success", style: "width: 150px;" %>
				</div>
				<div style="margin-top: 10px;">
					<%= link_to "お気に入り一覧", favolist_customer_path(current_customer), class: "btn btn-success", style: "width: 150px;" %><br>
				</div>
			</div>
		</div>

		<div class ="col-lg-9" >
			<table class="table table-striped">
				<% @photos.each do |photo| %>
				<tr>
					<td>
						<%= link_to photo_path(photo.id) do %>
							<%= attachment_image_tag photo, :image, size: "300x200" %>
						<% end %>
						<%= link_to customer_path(photo.customer.id) do %>
							<%= attachment_image_tag(photo.customer, :profile_image, :fill, 100,100, fallback: "no_image.jpg", size: "100x100", class: "img-circle") %>
							<%= photo.customer.name %><br>
						<% end %>
					</td>
					<td>
						<div style="margin-top: 100px;">
						@<%= photo.place %>
						#<%= photo.tag %>
						</div>
                	</td>
               		<td>
               			<div style="margin-top: 100px;">
						<% if photo.favorited_by?(current_customer) %>
						<%= link_to photo_favorites_path(photo), method: :delete do %>
						<span class="glyphicon glyphicon-heart-empty" aria-hidden="true" style="color: red;"></span>
						<%= photo.favorites.count %> いいね
						<% end %>
						<% else %>
						<%= link_to photo_favorites_path(photo), method: :post do %>
						<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
						<%= photo.favorites.count %> いいね
						<% end %>
						<% end %>
						<% if photo.customer.id != current_customer.id %>
						<div style="margin-top: 10px;">
						<% if current_customer.following?(photo.customer) %>
        				<%= link_to 'フォローやめる', unfollow_path(photo.customer.id), method: :POST, class: "btn btn-default" %>
      					<% else %>
        				<%= link_to 'フォローする', follow_path(photo.customer.id), method: :POST, class: "btn btn-success" %>
      					<% end %>
						</div>
						<% end %>
						</div>
					</td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/customers/show.html.erb
<div class ="container">
	<div class ="row">
		<div class="col-lg-3" style="margin-top: 30px;">
		  <div class="center_text">
			<%= attachment_image_tag(@customer, :profile_image, :fill, 200,200, fallback: "no_image.jpg", size: '200x200', style: "border-radius: 70%;") %>
			<h3><%= @customer.name %></h3>
			<div style="margin-top: 10px;">
				<%= link_to "フォロー数： #{@customer.follower.count}", follower_customer_path(@customer), class: "btn btn-default" %>
			</div>

			<div style="margin-top: 10px;">
				<%=link_to "フォロワー数： #{@customer.followed.count}", followed_customer_path(@customer), class: "btn btn-success" %>
			</div>

			<% if @customer.id == current_customer.id %>
			<div style="margin-top: 10px;">
				<%= link_to "プロフィール編集", edit_customer_path(current_customer), class: "btn btn-default", style: "width: 150px;" %><br>
			</div>
			<% end %>
			<div style="margin-top: 10px;">
				<%= link_to "投稿する", new_photo_path, class: "btn btn-success", style: "width: 150px;" %>
			</div>
			<div style="margin-top: 10px;">
				<%= link_to "お気に入り一覧", favolist_customer_path(@customer), class: "btn btn-success", style: "width: 150px;" %><br>
			</div>
	      </div>
		</div>
		<div class="col-lg-9" style="margin-top: 30px;">
			<% @customer.photos.each do |photo| %>
			<table class="table table-striped">
				<tr>
					<%= link_to photo_path(photo.id) do %>
					<%= attachment_image_tag photo, :image, size: "300x200" %>
					<% end %>
				</tr>
				<tr>
					@<%= photo.place %>
					#<%= photo.tag %>
					<% if photo.favorited_by?(current_customer) %>
					<%= link_to photo_favorites_path(photo), method: :delete do %>
					<span class="glyphicon glyphicon-heart-empty" aria-hidden="true" style="color: red;"></span>
					<%= photo.favorites.count %> いいね
					<% end %>
					<% else %>
					<%= link_to photo_favorites_path(photo), method: :post do %>
					<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
					<%= photo.favorites.count %> いいね
					<% end %>
					<% end %>
					<% if photo.customer.id == current_customer.id %>
					<%= link_to "編集する", edit_photo_path(photo), class: "btn btn-primary" %>
					<%= link_to "削除する", photo_path(photo), method: :delete, class: "btn btn-danger" %>
					<% end %>
					<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>